platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.coding.net/cker/EZBSpecs.git'

target 'CNKChat' do
  pod 'Masonry'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'YTKKeyValueStore'
  pod 'YYCache'
  pod 'Aspects'
  pod 'EBBadgeView'
  pod 'IQKeyboardManager', '~> 3.3.7'
  pod 'MJRefresh'
  pod 'EBEmptyView'
  pod 'ReactiveCocoa' , '~> 2.5.0'
  pod 'FTPopOverMenu'
  pod 'YYText'
  pod 'LKDBHelper'
  pod 'NSXtensions'
  pod 'FCFileManager'
  pod 'CocoaSecurity'
  pod 'TZImagePickerController'
  pod 'EZBCategories'
  pod 'AYViewCorner'
  pod 'TCBlobDownload'
  pod 'MNFrameRate'
  pod 'MBProgressHUD'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Block-KVO', :git => 'https://github.com/Tricertops/Block-KVO.git'
  pod 'WebViewJavascriptBridge', '~> 5.0'
end
